In [9]:
import pandas as pd

In [10]:
df_laptop = pd.read_csv('laptop_price.csv', encoding='unicode_escape')

In [11]:
df_laptop.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94

# Creating a Conditional column from 2 chocies np.where()

syntax :- np.where(condition, value_if_true, value_if_false)

In [12]:
import numpy as np

In [13]:
# Creating a array based on price .
np.where(df_laptop['Price_euros']>2000, 'Expensive', 'Inexpensive')

array(['Inexpensive', 'Inexpensive', 'Inexpensive', ..., 'Inexpensive',
       'Inexpensive', 'Inexpensive'], shape=(1303,), dtype='<U11')

In [15]:
# adding a new column to the dataframe
df_laptop['Price_desc'] = np.where(df_laptop['Price_euros']>2000,'Expensive', 'Inexpensive')

In [19]:
df_laptop.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_desc
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Inexpensive
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Inexpensive

In [27]:
# counting the no of values in Price_desc
df_laptop.value_counts('Price_desc')

Price_desc
Inexpensive    1166
Expensive       137
Name: count, dtype: int64

## Exercise .

In [46]:
# craeting an array based on Ram system 
Ram_desc = np.where(df_laptop['Ram'].str[0:1] >= '16', 'good', 'notbad' )

In [47]:
Ram_desc

array(['good', 'good', 'good', ..., 'good', 'good', 'good'],
      shape=(1303,), dtype='<U6')

In [54]:
## addind the above created row to th df
df_laptop.insert(8, 'Ram_descp',Ram_desc )

In [55]:
df_laptop.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Ram_descp,Memory,Gpu,OpSys,Weight,Price_euros,Price_desc,Ram_desc
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,good,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Inexpensive,good
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,good,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Inexpensive,good

In [61]:
df_laptop.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Ram_descp,Memory,Gpu,OpSys,Weight,Price_euros,Price_desc
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,good,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Inexpensive
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,good,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Inexpensive

In [59]:
# df_laptop.drop('Ram_desc', axis=1, inplace=True)

In [60]:
# df_laptop['Ram_desc']