In [1]:
# import pandas
import pandas as pd

In [2]:
df = pd.read_csv('bestsellers with categories.csv')

# Create a DataFrame

In [3]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [4]:
# get access to the shape attribute
df.shape

(550, 7)

In [5]:
# find the data types of each column
df.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
dtype: object

# Display a DataFrame

In [6]:
# show first 5 rows in a dataframe 
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [7]:
# describe basic statistics of the dataframe (mean, std, min, max) 
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

# Add a new Column with an array

In [8]:
#   create a column named 'Critic Rating' that should have random integer numbers between 1 and 4
# 1. import numpy and create 550 random integer numbers between 1 and 4
import numpy as np
cr_int = np.random.randint(1,4, size=10) # generate random integer num
cr = (np.random.rand(len(df))*4).round(2)

# 2. add new 'Critic Rating' column to dataframe using the random numbers created
df['Critic Rating'] = cr

In [9]:
df.tail()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,0.92
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,3.66
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,2.70
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,3.38
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,3.09

# Basic Attributes, Methods and Functions

In [10]:
# get access to the columns attribute
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre',
       'Critic Rating'],
      dtype='object')

## Selecting Two or More Columns from a Dataframe

In [11]:
# move the new 'Critic Rating' column between the columns "User Rating" and "Reviews" Then update the dataframe
df[['Name', 'Author', 'User Rating', 'Critic Rating', 'Reviews', 'Price', 'Year', 'Genre'
       ]]

,Name,Author,User Rating,Critic Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,2.11,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,1.53,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,0.25,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,2.13,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,3.88,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,0.92,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,3.66,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,2.70,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,3.38,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,3.09,14331,8,2019,Non Fiction

# Operations on Dataframes

In [20]:
# create a column named "Average Rating" by using the following formula: Average Rating = (User Rating + Critic Rating)/2
df['Average Rating'] = (df['User Rating'] +df['Critic Rating'])/2

In [23]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating,Average Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,2.11,3.405
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,1.53,3.065
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,0.25,2.475
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,2.13,3.415
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,3.88,4.340

In [24]:
# use the round function to round the values of the dataframe to 1 decimal and update the dataframe
df.round(1).head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating,Average Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,2.1,3.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,1.5,3.1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,0.2,2.5
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,2.1,3.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,3.9,4.3

# Value Counts

In [37]:
# count elements in "Genre" column by category and return the relative frequency 
df.value_counts('Genre') # show no of diff values
df["Genre"].value_counts(normalize=True)

Genre
Non Fiction    0.563636
Fiction        0.436364
Name: proportion, dtype: float64

# Rename Columns

In [34]:
# rename columns "User Rating," "Critic Rating" and "Average Rating" to "UR," "CR" and "AR" then update the dataframe with the inplace paraneter
df.rename(columns={'User Rating':'ur','Critic Rating':'cr',
                   'Average Rating':'ar'}, inplace=True)

# sort

In [35]:
df.sort_values(['ar','cr'], ascending=False)

,Name,Author,ur,Reviews,Price,Year,Genre,cr,ar
477,The Very Hungry Caterpillar,Eric Carle,4.9,19546,5,2014,Fiction,3.97,4.435
153,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,4.9,19622,30,2016,Fiction,3.95,4.425
488,The Wonderful Things You Will Be,Emily Winfield Martin,4.9,8842,10,2018,Fiction,3.94,4.420
476,The Very Hungry Caterpillar,Eric Carle,4.9,19546,5,2013,Fiction,3.90,4.400
203,Kitchen Confidential Updated Edition: Adventur...,Anthony Bourdain,4.8,2507,8,2018,Non Fiction,3.96,4.380
...,...,...,...,...,...,...,...,...,...
22,Allegiant,Veronica Roth,3.9,6310,13,2013,Fiction,0.33,2.115
182,Inferno,Dan Brown,4.1,29651,14,2013,Fiction,0.01,2.055
307,StrengthsFinder 2.0,Gallup,4.0,5069,17,2012,Non Fiction,0.07,2.035
132,Go Set a Watchman: A Novel,Harper Lee,3.6,14982,19,2015,Fiction,0.09,1.845
353,The Casual Vacancy,J.K. Rowling,3.3,9372,12,2012,Fiction,0.12,1.710