In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('players_20.csv')

In [6]:
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [7]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Selecting with a single value
iloc[row_position, column_position]

In [10]:
#  the height of L.Messi
df.iloc[0,3]

np.int64(170)

In [12]:
#  the weight of Cristiano Ronaldo 
df.iloc[1,4]

np.int64(83)

In [13]:
#  all rows inside the 'height_cm column'
df.iloc[:,4]

short_name
L. Messi             72
Cristiano Ronaldo    83
Neymar Jr            68
J. Oblak             87
E. Hazard            74
                     ..
Shao Shuai           79
Xiao Mingjie         66
Zhang Wei            75
Wang Haijian         74
Pan Ximing           78
Name: weight_kg, Length: 18278, dtype: int64

In [14]:
# get all columns that correspond to the index 'L. Messi'
df.iloc[0,:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

# Selecting with a list of values

In [19]:
#  all data about L.Messi and Cristiano Ronaldo
df.iloc[:2,:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [20]:
#  the height and weight of L.Messi
df.iloc[:2, 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [22]:
#  the height and weight of L.Messi
df.iloc[0,3:5]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [24]:
# get height and weight of L.Messi and Cristiano Ronaldo
df.iloc[:2, 3:5]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

# Selecting a range of data with a slice
start:stop (Note that the start is included but the stop is excluded)

In [17]:
# slice column labels. From column "age" to column "club"
# players = ['L. Messi', 'Cristiano Ronaldo']
df.iloc[0:2, 2:]

                          dob  height_cm  weight_kg nationality          club
short_name
L. Messi           1987-06-24        170         72   Argentina  FC Barcelona
Cristiano Ronaldo  1985-02-05        187         83    Portugal      Juventus

In [18]:
# slice index labels. From top1 to top10 player
# columns = ['age', 'dob', 'height_cm', 'weight_kg']
df.iloc[:11, 1:5]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71
K. Mbappé           20  1998-12-20        178         73

# Selecting with conditions
iloc cannot accept a boolean Series, but only a boolean list. We have to use the list() function to convert a Series into a boolean list.

In [31]:
df[df['height_cm']>180].iloc[:, 2:5]

                          dob  height_cm  weight_kg
short_name
Cristiano Ronaldo  1985-02-05        187         83
J. Oblak           1993-01-07        188         87
K. De Bruyne       1991-06-28        181         70
M. ter Stegen      1992-04-30        187         85
V. van Dijk        1991-07-08        193         92
...                       ...        ...        ...
P. Martin          1999-01-05        188         84
Shao Shuai         1997-03-10        186         79
Zhang Wei          2000-05-16        186         75
Wang Haijian       2000-08-02        185         74
Pan Ximing         1993-01-11        182         78

[9744 rows x 3 columns]

In [35]:
df[ (df['height_cm']>180) & (df['nationality']=='Argentina') ].iloc[:, 2:5]

                       dob  height_cm  weight_kg
short_name
M. Icardi       1993-02-19        181         75
G. Higuaín      1987-12-10        186         89
E. Garay        1986-10-10        189         90
N. Otamendi     1988-02-12        183         81
G. Rulli        1992-05-20        189         84
...                    ...        ...        ...
T. Durso        1999-02-26        185         80
J. Hass         1998-03-27        186         88
R. Ferrario     2000-04-30        186         76
L. Finochietto  1997-04-25        186         77
N. Forastiero   1998-07-16        182         79

[350 rows x 3 columns]