In [1]:
import pandas as pd

In [ ]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [4]:
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

# Selecting with a single value

syntax :- loc[row_label, column_label]

In [6]:
# geting all data of individual row 
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [7]:
# getting specfic data from a row 
df.loc['L. Messi','club']
# get the data of messi`s club name

'FC Barcelona'

In [8]:
df.loc['Neymar Jr','dob' ]
# getting nymer`s date ob birth

'1992-02-05'

In [10]:
# get all rows of a specfic column 
df.loc[:,'nationality'].head(3)

short_name
L. Messi             Argentina
Cristiano Ronaldo     Portugal
Neymar Jr               Brazil
Name: nationality, dtype: object

In [11]:
# get all data of a row or data of nymar 
df.loc['Neymar Jr']

long_name      Neymar da Silva Santos Junior
age                                       27
dob                               1992-02-05
height_cm                                175
weight_kg                                 68
nationality                           Brazil
club                     Paris Saint-Germain
Name: Neymar Jr, dtype: object

# Selecting with a list of values

In [13]:
df.loc[['Cristiano Ronaldo', 'Neymar Jr']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

In [14]:
df.loc[['L. Messi', 'Neymar Jr'],'height_cm']

short_name
L. Messi     170
Neymar Jr    175
Name: height_cm, dtype: int64

In [15]:
df.loc[['L. Messi', 'Cristiano Ronaldo', 'Neymar Jr'],['age', 'height_cm','weight_kg']]

                   age  height_cm  weight_kg
short_name
L. Messi            32        170         72
Cristiano Ronaldo   34        187         83
Neymar Jr           27        175         68

# Selecting a range of data with a slice

start:stop:step (Note that contrary to usual python slices, both the start and the stop are included)

In [16]:
players = ['L. Messi', 'Cristiano Ronaldo']
# slicing the column 
df.loc[players, 'age':'nationality' ]

                   age         dob  height_cm  weight_kg nationality
short_name
L. Messi            32  1987-06-24        170         72   Argentina
Cristiano Ronaldo   34  1985-02-05        187         83    Portugal

In [17]:
# slice index labels
columns = ['age', 'dob', 'height_cm', 'weight_kg']
# slicing first 10 players with required columns
df.loc['L. Messi':'M. Salah', columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

# Selecting with conditions

In [22]:
# selecting the players age 40 above 
columns = ['age', 'dob', 'height_cm', 'weight_kg'] 
df.loc[df['age']>40, columns]

              age         dob  height_cm  weight_kg
short_name
G. Buffon      41  1978-01-28        192         92
Hilton         41  1977-09-13        180         78
C. Lucchetti   41  1978-06-26        182         69
F. Kippe       41  1978-01-17        194         97
C. Muñoz       42  1977-07-01        177         73
H. Sulaimani   42  1977-01-21        173         70

In [23]:
df.loc[(df['height_cm']>180) & (df['weight_kg']>80), :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
K. Koulibaly,Kalidou Koulibaly,28,1991-06-20,187,89,Senegal,Napoli
...,...,...,...,...,...,...,...
B. Sinzig,Basil Sinzig,19,1999-12-21,191,81,Switzerland,Neuchâtel Xamax
J. Wright,Joe Wright,18,2001-04-10,185,82,England,Millwall
D. Mackay,Devlin Mackay,22,1997-01-23,191,81,Scotland,Kilmarnock
P. Królczyk,Patryk Królczyk,25,1994-05-10,188,81,Poland,Piast Gliwice
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC