In [1]:
import pandas as pd

In [2]:

# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

# Selecting with a single value

iloc[row_position, column_position]

In [4]:
# 0th row 5th column
df.iloc[0,5]

'Argentina'

In [5]:
 # get all rows inside the 'weight_kg column'
df.iloc[:,4]

short_name
L. Messi             72
Cristiano Ronaldo    83
Neymar Jr            68
J. Oblak             87
E. Hazard            74
                     ..
Shao Shuai           79
Xiao Mingjie         66
Zhang Wei            75
Wang Haijian         74
Pan Ximing           78
Name: weight_kg, Length: 18278, dtype: int64

In [7]:
# selecting all the datas of a particular row
df.iloc[2,:]

long_name      Neymar da Silva Santos Junior
age                                       27
dob                               1992-02-05
height_cm                                175
weight_kg                                 68
nationality                           Brazil
club                     Paris Saint-Germain
Name: Neymar Jr, dtype: object

# Selecting with a list of values

In [9]:
# all the colums of first 2 rows
df.iloc[[0,1]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [10]:
#show only weight_kg column of 2 rows one and two
df.iloc[[1,2],3]

short_name
Cristiano Ronaldo    187
Neymar Jr            175
Name: height_cm, dtype: int64

In [20]:
# height and weight column of 0th row
df.iloc[0,[3,4]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [31]:
df.iloc[[0,1],[5,6]]

                  nationality          club
short_name
L. Messi            Argentina  FC Barcelona
Cristiano Ronaldo    Portugal      Juventus

# Selecting a range of data with a slice

start:stop (Note that the start is included but the stop is excluded)

In [16]:

# slice column labels age/club
# players = ['L. Messi', 'Cristiano Ronaldo']
players = [0, 1]

df.iloc[players,1:6]

                   age         dob  height_cm  weight_kg nationality
short_name
L. Messi            32  1987-06-24        170         72   Argentina
Cristiano Ronaldo   34  1985-02-05        187         83    Portugal

In [22]:
# slice index labels (top1 to top10 player)
# columns = ['age', 'dob', 'height_cm', 'weight_kg']
columns = [1,2,3,4] 

df.iloc[1:10, [1,2,3,4]]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

# Selecting with conditions

iloc cannot accept a boolean Series, but only a boolean list. We have to use the list() function to convert a Series into a boolean list.

In [25]:
# one condition: select player with height above 180cm
# columns = ['age', 'dob', 'height_cm', 'weight_kg']
columns = [1,2,3,4]

df.iloc[list(df['height_cm']>180),columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [30]:
# multiple conditions
df.iloc[list((df['height_cm']> 180 ) & (df['weight_kg']>80) ) , : ]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
K. Koulibaly,Kalidou Koulibaly,28,1991-06-20,187,89,Senegal,Napoli
...,...,...,...,...,...,...,...
B. Sinzig,Basil Sinzig,19,1999-12-21,191,81,Switzerland,Neuchâtel Xamax
J. Wright,Joe Wright,18,2001-04-10,185,82,England,Millwall
D. Mackay,Devlin Mackay,22,1997-01-23,191,81,Scotland,Kilmarnock
P. Królczyk,Patryk Królczyk,25,1994-05-10,188,81,Poland,Piast Gliwice
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC