In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [4]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# query()

In [6]:
df.query('age>34')

df[df['age']>34].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria

In [16]:
df.query("age>34 and nationality == 'Portugal' ")

df[(df['age']>34) & (df['nationality']=='Portugal')]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
Quaresma,Ricardo Andrade Quaresma Bernardo,35,1983-09-26,175,67,Portugal,Beşiktaş JK
José Fonte,José Miguel da Rocha Fonte,35,1983-12-22,187,81,Portugal,LOSC Lille
Beto,António Alberto Bastos Pimparel,37,1982-05-01,182,81,Portugal,Göztepe SK
Tarantini,Ricardo José Vaz Alves Monteiro,35,1983-10-07,188,78,Portugal,Rio Ave FC
Ricardo Costa,Ricardo Miguel Moreira da Costa,38,1981-05-16,184,82,Portugal,Boavista FC
João Pereira,João Pedro da Silva Pereira,35,1984-02-25,172,66,Portugal,Trabzonspor
Bruno Alves,Bruno Eduardo Regufe Alves,37,1981-11-27,189,83,Portugal,Parma
Eduardo,Eduardo dos Reis Carvalho,36,1982-09-19,188,84,Portugal,SC Braga

In [19]:
df.query('not(age>34)')

df[~(df['age']>34)]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [21]:
df.query('height_cm/100 == 1.8')
df[df['height_cm']/100 == 1.8]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Reus,Marco Reus,30,1989-05-31,180,71,Germany,Borussia Dortmund
A. Di María,Ángel Fabián Di María Hernández,31,1988-02-14,180,69,Argentina,Paris Saint-Germain
F. de Jong,Frenkie de Jong,22,1997-05-12,180,74,Netherlands,FC Barcelona
D. Alaba,David Olatukunbo Alaba,27,1992-06-24,180,78,Austria,FC Bayern München
B. Matuidi,Blaise Matuidi,32,1987-04-09,180,75,France,Juventus
...,...,...,...,...,...,...,...
M. Roberts,Morgan Roberts,18,2000-12-22,180,74,England,Northampton Town
O. Bundgaard,Oliver Bundgaard,18,2001-06-15,180,75,Denmark,Randers FC
D. Bowry,Daniel Bowry,21,1998-04-29,180,67,Antigua & Barbuda,Cheltenham Town
P. Phillips,Pierce Phillips,20,1998-09-28,180,72,Republic of Ireland,Cork City
E. Tweed,Evan Tweed,20,1999-03-01,180,72,Republic of Ireland,Derry City

In [30]:
# select players that were born after 1990

# check out data types
df.dtypes

# convert "dob" column to datetime type
df['dob'] = df['dob'].astype('datetime64[ns]')
df['dob'].dtypes

# query
df.query('dob.dt.year > 1990')

df[df['dob'].dt.year >1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC