In [2]:
import pandas as pd
import numpy as np

 1 creating a dataframe from array 

1.1 option 1

In [3]:
# creating an array
data = np.array([[1,3],[2,5],[3,6]])

In [4]:
# Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
                 columns=['col1', 'col2'])
df

      col1  col2
row1     1     3
row2     2     5
row3     3     6

1.2 option 2

In [5]:
# Creating a array with list
data = [[1,3],[2,5],[3,6]]

In [6]:
# Creating a dataframe 
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
                 columns=['col1', 'col2'])
df

      col1  col2
row1     1     3
row2     2     5
row3     3     6

2. Creating data frame using dictionary

In [7]:
# lists
dept = ['civil', 'mech', 'eee', 'ece', 'tech']
students = [30, 20, 25, 40, 60]

In [8]:
dict = {'Dept':dept , 'Students':students}

In [9]:
df = pd.DataFrame(dict)
df

    Dept  Students
0  civil        30
1   mech        20
2    eee        25
3    ece        40
4   tech        60

3. Creating a data frame a csv file

In [10]:
# reading the csv file 
df = pd.read_csv('people.csv')
# first five and last five .
df

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer
...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer
996,997,ECddaFEDdEc4FAB,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator
997,998,2adde51d8B8979E,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor
998,999,Fb2FE369D1E171A,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person
999,1000,8b756f6231DDC6e,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability"

In [11]:
# first five rows
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer

In [12]:
# last five rows 
df.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer
996,997,ECddaFEDdEc4FAB,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator
997,998,2adde51d8B8979E,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor
998,999,Fb2FE369D1E171A,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person
999,1000,8b756f6231DDC6e,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability"

In [13]:
# required no of rows 
df.head(10)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer
5,6,aF75e6dDEBC5b66,Sherry,Caldwell,Male,kaitlin13@example.net,8537800927,1917-08-06,Higher education lecturer
6,7,efeb05c7Cc94EA3,Ernest,Hoffman,Male,jeffharvey@example.com,093.655.7480x7895,1984-12-22,Health visitor
7,8,fb1BF3FED57E9d7,Doris,Andersen,Male,alicia33@example.org,4709522945,2016-12-02,Air broker
8,9,421fAB9a3b98F30,Cheryl,Mays,Male,jake50@example.com,013.820.4758,2012-12-16,"Designer, multimedia"
9,10,4A42Fe10dB717CB,Harry,Mitchell,Male,lanechristina@example.net,(560)903-5068x4985,1953-06-29,Insurance account manager

In [14]:
df.shape

(1000, 9)

In [43]:
# Display all rows
pd.set_option('display.max_rows', 1000)
df

1.2 Syntax 2

In [54]:
# Select a column with 
df.Phone.head()

0          857.139.8239
1       +1-950-759-8687
2         (599)782-0605
3       +1-939-130-6258
4    (390)417-1635x3010
Name: Phone, dtype: object

Selecting multiple columns

In [57]:
#Selecting 2 columns using[[]]
df[['First Name', 'Phone']].head()

  First Name               Phone
0     Shelia        857.139.8239
1         Jo     +1-950-759-8687
2     Sheryl       (599)782-0605
3    Whitney     +1-939-130-6258
4    Lindsey  (390)417-1635x3010

In [59]:
# data type of the columns
type(df[['First Name', 'Phone']])

pandas.core.frame.DataFrame

In [64]:
# select 2 or more colummns using[[]]
df[['First Name','Last Name' ,'Phone']].head()

  First Name Last Name               Phone
0     Shelia   Mahoney        857.139.8239
1         Jo    Rivers     +1-950-759-8687
2     Sheryl    Lowery       (599)782-0605
3    Whitney    Hooper     +1-939-130-6258
4    Lindsey      Rice  (390)417-1635x3010