In [1]:
import pandas as pd
df = pd.read_csv('organizations.csv')
df.head()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991

Rename columns

In [5]:
# renaming the single column
df.rename(columns={'Website': 'site'})

,Index,Organization Id,Name,site,Country,Description,Founded,Industry,Number of employees
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991
...,...,...,...,...,...,...,...,...,...
995,996,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547
996,997,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723
997,998,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355
998,999,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825
999,1000,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467

In [7]:
# renaming multiple columns
df.rename(columns={'Website': 'site',
                   'Number of employees':'no of emply' }, inplace=True)

In [9]:
df

,Index,Organization Id,Name,site,Country,Description,Founded,Industry,no of emply
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991
...,...,...,...,...,...,...,...,...,...
995,996,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547
996,997,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723
997,998,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355
998,999,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825
999,1000,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467

Renaming index

In [12]:
df.rename(index={'1':'a', '2':'b'}, inplace=True)

In [13]:
df

,Index,Organization Id,Name,site,Country,Description,Founded,Industry,no of emply
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
a,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
b,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991
...,...,...,...,...,...,...,...,...,...
995,996,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547
996,997,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723
997,998,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355
998,999,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825
999,1000,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467