In [1]:
import pandas as pd
df = pd.read_csv('people.csv')

Getting individual column from data frame

1.1 syntax 1

In [3]:
# select the column with square bracket []
df['First Name']

0        Shelia
1            Jo
2        Sheryl
3       Whitney
4       Lindsey
         ...
995        Kurt
996       Donna
997       Cathy
998    Jermaine
999         Lee
Name: First Name, Length: 1000, dtype: object

In [5]:
# find the data type of a column
type(df['First Name'])

pandas.core.series.Series

In [7]:
#series : attributes and methods
df['First Name'].index
df['First Name'].head()

RangeIndex(start=0, stop=1000, step=1)

syntax 2

In [8]:
# Select a column with 
df.Phone

0               857.139.8239
1            +1-950-759-8687
2              (599)782-0605
3            +1-939-130-6258
4         (390)417-1635x3010
               ...
995             021.775.2933
996     001-149-710-7799x721
997    +1-750-774-4128x33265
998            (915)292-2254
999       079.752.5424x67259
Name: Phone, Length: 1000, dtype: object

Selecting Multiple Columns

In [10]:
#Selecting 2 columns using[[]]
df[['First Name', 'Phone']]

    First Name                  Phone
0       Shelia           857.139.8239
1           Jo        +1-950-759-8687
2       Sheryl          (599)782-0605
3      Whitney        +1-939-130-6258
4      Lindsey     (390)417-1635x3010
..         ...                    ...
995       Kurt           021.775.2933
996      Donna   001-149-710-7799x721
997      Cathy  +1-750-774-4128x33265
998   Jermaine          (915)292-2254
999        Lee     079.752.5424x67259

[1000 rows x 2 columns]

In [11]:
# data type of the columns
type(df[['First Name', 'Phone']])

pandas.core.frame.DataFrame

In [12]:
# select 2 or more colummns using[[]]
df[['First Name','Last Name' ,'Phone']]

  First Name Last Name               Phone
0     Shelia   Mahoney        857.139.8239
1         Jo    Rivers     +1-950-759-8687
2     Sheryl    Lowery       (599)782-0605
3    Whitney    Hooper     +1-939-130-6258
4    Lindsey      Rice  (390)417-1635x3010