In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('people.csv')

1. assign() :- using assign function for adding multiple values

In [4]:
# creating an new arrays with random numbers
score1 = np.random.randint(1,100, size=1000)
score2 = np.random.randint(1,100, size=1000)

In [9]:
# Creating a series using the random numbers 
s1 = pd.Series(score1, index=np.arange(0,1000))
s2 = pd.Series(score2, index=np.arange(0,1000))

In [13]:
# using assign() to add multiple columns
# assing method only create a copy overide using assign it to original dataframe
df = df.assign(Score1 = s1, Score2= s2)
df

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Score1,Score2
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,88,4
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,78,17
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,23,59
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,59,49
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,96,15
...,...,...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer,29,15
996,997,ECddaFEDdEc4FAB,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator,33,51
997,998,2adde51d8B8979E,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor,50,64
998,999,Fb2FE369D1E171A,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person,74,10
999,1000,8b756f6231DDC6e,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability",20,39

2. insert() :- insert method used to insert a column at specfic position or index

In [16]:
# using insert() to add a column to the specfic index
# syntax :- insert(indes value, name of the column, value)
df.insert(2, 'random', s2)
df

,Index,User Id,random,test,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Score1,Score2
0,1,8717bbf45cCDbEe,4,4,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,88,4
1,2,3d5AD30A4cD38ed,17,17,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,78,17
2,3,810Ce0F276Badec,59,59,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,23,59
3,4,BF2a889C00f0cE1,49,49,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,59,49
4,5,9afFEafAe1CBBB9,15,15,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,96,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,15,15,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer,29,15
996,997,ECddaFEDdEc4FAB,51,51,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator,33,51
997,998,2adde51d8B8979E,64,64,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor,50,64
998,999,Fb2FE369D1E171A,10,10,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person,74,10
999,1000,8b756f6231DDC6e,39,39,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability",20,39