In [2]:
import pandas as pd
df = pd.read_csv('organizations.csv')
df.head()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991

1. Sort a dataframe

In [4]:
# Sort by column
df.sort_values(by='Founded')

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
944,945,Ab2c152D2c10fA1,Montoya Group,http://www.henderson.net/,Micronesia,Progressive dedicated knowledge user,1970,Medical Equipment,6865
442,443,57A23e8bcf9d340,Larson and Sons,http://www.braun.com/,Jersey,Pre-emptive disintermediate flexibility,1970,Real Estate / Mortgage,3786
410,411,eE2D54F3Ad9c126,Cantrell-Glover,https://www.lowe-andrade.com/,Aruba,Reduced foreground firmware,1970,Facilities Services,313
420,421,8a3f4C30964e1Af,Small-Peters,http://www.graham-vazquez.com/,Russian Federation,Total mission-critical monitoring,1970,Computer Hardware,9212
...,...,...,...,...,...,...,...,...,...
237,238,dcaF3C5Ba029Ba8,Roberts Group,http://gamble-blake.com/,Somalia,Function-based even-keeled process improvement,2021,Individual / Family Services,8534
677,678,A3B8d27d51aae2f,"Hanson, Newman and Bradley",http://www.shepherd.com/,Algeria,Customizable fresh-thinking task-force,2021,Individual / Family Services,2135
413,414,e80c7A5efCd4FAd,Romero Ltd,http://fuller-schmidt.com/,Montserrat,Synergized exuding neural-net,2021,Glass / Ceramics / Concrete,4366
852,853,391e22a22E6C77A,"Sanchez, Pugh and Decker",http://faulkner-anthony.com/,Chile,Progressive directional Graphic Interface,2022,Alternative Dispute Resolution,8917
867,868,183Edd689DBdE8f,Santana Group,https://kim.com/,Heard Island and McDonald Islands,Focused interactive Graphic Interface,2022,Fishery,8873

In [5]:
# sort descending by  one column
df.sort_values(by='Founded', ascending=False)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
852,853,391e22a22E6C77A,"Sanchez, Pugh and Decker",http://faulkner-anthony.com/,Chile,Progressive directional Graphic Interface,2022,Alternative Dispute Resolution,8917
867,868,183Edd689DBdE8f,Santana Group,https://kim.com/,Heard Island and McDonald Islands,Focused interactive Graphic Interface,2022,Fishery,8873
413,414,e80c7A5efCd4FAd,Romero Ltd,http://fuller-schmidt.com/,Montserrat,Synergized exuding neural-net,2021,Glass / Ceramics / Concrete,4366
895,896,f7441E4ACC9b9CA,"Hayes, Saunders and Richards",https://www.morris.biz/,Portugal,Customer-focused radical solution,2021,Medical Practice,2526
677,678,A3B8d27d51aae2f,"Hanson, Newman and Bradley",http://www.shepherd.com/,Algeria,Customizable fresh-thinking task-force,2021,Individual / Family Services,2135
...,...,...,...,...,...,...,...,...,...
74,75,D9b675D794bBA4e,Young LLC,http://mcintyre-blankenship.org/,Iran,Cross-platform fault-tolerant collaboration,1970,Political Organization,5683
70,71,B4Af39eFb508DEE,Mccann-Mcguire,http://www.fleming-farrell.org/,Lesotho,Front-line client-driven project,1970,Legal Services,5800
450,451,A66737cE0cCb2c6,Huerta PLC,https://www.byrd.org/,Gambia,Operative fault-tolerant alliance,1970,Dairy,4337
79,80,cebd8989bcd3aF8,"Hart, Williamson and Klein",http://burch-montgomery.org/,Suriname,Open-source well-modulated process improvement,1970,Management Consulting,4989
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994

In [6]:
# sort descending by multiple column
df.sort_values(['Founded', 'Number of employees'], ascending=False)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
852,853,391e22a22E6C77A,"Sanchez, Pugh and Decker",http://faulkner-anthony.com/,Chile,Progressive directional Graphic Interface,2022,Alternative Dispute Resolution,8917
867,868,183Edd689DBdE8f,Santana Group,https://kim.com/,Heard Island and McDonald Islands,Focused interactive Graphic Interface,2022,Fishery,8873
347,348,efFe2cB0Aacfdfb,"Morris, Villegas and English",http://www.stephenson.com/,Kenya,Multi-channeled cohesive moderator,2021,Sporting Goods,9089
237,238,dcaF3C5Ba029Ba8,Roberts Group,http://gamble-blake.com/,Somalia,Function-based even-keeled process improvement,2021,Individual / Family Services,8534
187,188,2eaA3c5D6CC37B9,Schneider-Elliott,https://molina.com/,Bahamas,Synchronized zero administration core,2021,Supermarkets,7306
...,...,...,...,...,...,...,...,...,...
558,559,BaB1Df6EAa15de3,English Ltd,https://www.hahn.com/,Marshall Islands,Multi-tiered disintermediate policy,1970,Recreational Facilities / Services,1820
205,206,9eEB46CbF04EEFF,"Beltran, Flores and Kelley",http://www.mcclain.org/,Argentina,Monitored optimal array,1970,Railroad Manufacture,1371
579,580,6bC62F2c0fcfb43,"Horne, Hartman and Flowers",http://www.erickson.net/,Lebanon,Profound homogeneous throughput,1970,Internet,1312
176,177,4b0Ff29BAc3B2FC,"Moran, Nichols and Kelly",http://irwin.com/,Solomon Islands,Adaptive tertiary data-warehouse,1970,Alternative Medicine,1124
410,411,eE2D54F3Ad9c126,Cantrell-Glover,https://www.lowe-andrade.com/,Aruba,Reduced foreground firmware,1970,Facilities Services,313

In [7]:
# sort descending by multipe=le columns and update original dataframe
df.sort_values(['Founded', 'Number of employees'], ascending=False,
               inplace=True)
df

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
852,853,391e22a22E6C77A,"Sanchez, Pugh and Decker",http://faulkner-anthony.com/,Chile,Progressive directional Graphic Interface,2022,Alternative Dispute Resolution,8917
867,868,183Edd689DBdE8f,Santana Group,https://kim.com/,Heard Island and McDonald Islands,Focused interactive Graphic Interface,2022,Fishery,8873
347,348,efFe2cB0Aacfdfb,"Morris, Villegas and English",http://www.stephenson.com/,Kenya,Multi-channeled cohesive moderator,2021,Sporting Goods,9089
237,238,dcaF3C5Ba029Ba8,Roberts Group,http://gamble-blake.com/,Somalia,Function-based even-keeled process improvement,2021,Individual / Family Services,8534
187,188,2eaA3c5D6CC37B9,Schneider-Elliott,https://molina.com/,Bahamas,Synchronized zero administration core,2021,Supermarkets,7306
...,...,...,...,...,...,...,...,...,...
558,559,BaB1Df6EAa15de3,English Ltd,https://www.hahn.com/,Marshall Islands,Multi-tiered disintermediate policy,1970,Recreational Facilities / Services,1820
205,206,9eEB46CbF04EEFF,"Beltran, Flores and Kelley",http://www.mcclain.org/,Argentina,Monitored optimal array,1970,Railroad Manufacture,1371
579,580,6bC62F2c0fcfb43,"Horne, Hartman and Flowers",http://www.erickson.net/,Lebanon,Profound homogeneous throughput,1970,Internet,1312
176,177,4b0Ff29BAc3B2FC,"Moran, Nichols and Kelly",http://irwin.com/,Solomon Islands,Adaptive tertiary data-warehouse,1970,Alternative Medicine,1124
410,411,eE2D54F3Ad9c126,Cantrell-Glover,https://www.lowe-andrade.com/,Aruba,Reduced foreground firmware,1970,Facilities Services,313

In [8]:
df.sort_values(['Country'], ascending=False)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
372,373,9dCfc8838153DfD,Saunders-Fitzgerald,http://banks.com/,Zimbabwe,Cloned solution-oriented utilization,1979,Think Tanks,6956
936,937,3FCbAacC60B08cC,Kelley-Cantu,https://rubio.com/,Zimbabwe,Programmable tangible groupware,2018,Library,5526
716,717,2D2dDf75458FEFF,Nelson PLC,http://fuentes.com/,Zimbabwe,Horizontal upward-trending collaboration,2000,Maritime,511
495,496,9D3Ec64eBDc768E,Jenkins Inc,https://evans.com/,Zimbabwe,Visionary radical approach,2019,Renewables / Environment,1864
180,181,E7EF4829bE63DcB,"Byrd, Wallace and Bryan",http://moore.com/,Zimbabwe,Networked high-level forecast,1975,Package / Freight Delivery,5371
...,...,...,...,...,...,...,...,...,...
607,608,91ba1665eEb4D22,"Cohen, Saunders and Curtis",https://todd.com/,Albania,Cloned modular benchmark,1972,Other Industry,1999
577,578,3D41753AADAc2FB,Mueller Group,https://www.nichols.com/,Albania,Function-based value-added moratorium,1972,Graphic Design / Web Design,956
247,248,BbA52b87BB6A32f,King Inc,https://www.fry.org/,Afghanistan,Digitized attitude-oriented approach,1985,Apparel / Fashion,6819
933,934,8a9190A50adf241,"Riddle, Leach and Gould",http://brown.biz/,Afghanistan,Programmable holistic collaboration,1991,Ranching,3695
12,13,4EB9d3E5cF79b91,"Bernard, Payne and Spencer",http://williamson.net/,Afghanistan,Polarized dynamic projection,1990,Transportation,730