In [1]:
import pandas as pd
df = pd.read_csv('organizations.csv')
df.head()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991

1 Create Index

In [3]:
import numpy as np 
import random

In [10]:
# creating a non repetive value for the index
new_index = np.arange(0,1000)

In [11]:
# shuffling the indexes
random.shuffle(new_index)

In [15]:
# creating a new column with new index
df.insert(1, 'New_Index', new_index)

ValueError: cannot insert New_Index, already exists

In [18]:
df

,Index,New_Index,New_index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,844,844,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,606,606,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,508,508,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,72,72,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,281,281,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991
...,...,...,...,...,...,...,...,...,...,...,...
995,996,367,367,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547
996,997,97,97,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723
997,998,208,208,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355
998,999,949,949,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825
999,1000,557,557,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467

Set Index

In [21]:
# Set new_index column as index
df.set_index('New_index', inplace=True)
df

,Index,New_Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
New_index,,,,,,,,,,
844,1,844,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
606,2,606,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
508,3,508,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
72,4,72,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
281,5,281,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991
...,...,...,...,...,...,...,...,...,...,...
367,996,367,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547
97,997,97,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723
208,998,208,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355
949,999,949,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825
557,1000,557,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467

3. Sort Index

In [22]:
# sort data frame by new index
df.sort_index()

,Index,New_Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
New_index,,,,,,,,,,
0,193,0,21A92A2a6D4Faa2,Shelton PLC,https://medina.info/,Saudi Arabia,Multi-layered client-server Internet solution,1973,Food Production,9909
1,66,1,eA78bec48c0fBCe,"Blevins, Love and Banks",http://knight-stevenson.com/,Samoa,Multi-layered needs-based solution,1977,Renewables / Environment,1891
2,493,2,52bc0070051fBF9,Potter-Solis,http://riley.biz/,Kenya,Horizontal asymmetric interface,1993,Entertainment / Movie Production,4209
3,299,3,a8fd24e2Bb7d0fD,Kirk-Moody,https://oneal-avery.com/,Cameroon,Operative solution-oriented process improvement,1971,Government Administration,4110
4,460,4,Bed9fEADDC70a6c,Singh-Bartlett,https://www.forbes-joyce.com/,Slovenia,Digitized optimizing time-frame,1988,Wireless,866
...,...,...,...,...,...,...,...,...,...,...
995,410,995,8bBC7a4bA6388F6,"Peters, Booker and Ramirez",http://www.mcdowell.com/,Korea,Cross-group executive database,1976,Newspapers / Journalism,4559
996,936,996,2E92e71EB9E6Fb7,"Hodges, Good and Kirby",http://www.velasquez.biz/,Haiti,Operative optimizing data-warehouse,2012,Computer Hardware,5703
997,441,997,ACC61A49398bDD4,Collier-Howe,http://pratt.com/,American Samoa,Polarized high-level complexity,1972,Education Management,1416
998,933,998,e1e2eDe231A49AA,Silva-Ray,https://www.campbell-cowan.org/,Haiti,Realigned full-range utilization,2002,Capital Markets / Hedge Fund / Private Equity,7913
999,708,999,C6eB96aCC73BAa0,Bradshaw-Orozco,http://stewart.com/,Burundi,Focused multi-state matrices,1973,Information Technology / IT,3619

In [23]:
# sort descending by index
df.sort_index(ascending=False)

,Index,New_Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
New_index,,,,,,,,,,
999,708,999,C6eB96aCC73BAa0,Bradshaw-Orozco,http://stewart.com/,Burundi,Focused multi-state matrices,1973,Information Technology / IT,3619
998,933,998,e1e2eDe231A49AA,Silva-Ray,https://www.campbell-cowan.org/,Haiti,Realigned full-range utilization,2002,Capital Markets / Hedge Fund / Private Equity,7913
997,441,997,ACC61A49398bDD4,Collier-Howe,http://pratt.com/,American Samoa,Polarized high-level complexity,1972,Education Management,1416
996,936,996,2E92e71EB9E6Fb7,"Hodges, Good and Kirby",http://www.velasquez.biz/,Haiti,Operative optimizing data-warehouse,2012,Computer Hardware,5703
995,410,995,8bBC7a4bA6388F6,"Peters, Booker and Ramirez",http://www.mcdowell.com/,Korea,Cross-group executive database,1976,Newspapers / Journalism,4559
...,...,...,...,...,...,...,...,...,...,...
4,460,4,Bed9fEADDC70a6c,Singh-Bartlett,https://www.forbes-joyce.com/,Slovenia,Digitized optimizing time-frame,1988,Wireless,866
3,299,3,a8fd24e2Bb7d0fD,Kirk-Moody,https://oneal-avery.com/,Cameroon,Operative solution-oriented process improvement,1971,Government Administration,4110
2,493,2,52bc0070051fBF9,Potter-Solis,http://riley.biz/,Kenya,Horizontal asymmetric interface,1993,Entertainment / Movie Production,4209
1,66,1,eA78bec48c0fBCe,"Blevins, Love and Banks",http://knight-stevenson.com/,Samoa,Multi-layered needs-based solution,1977,Renewables / Environment,1891
0,193,0,21A92A2a6D4Faa2,Shelton PLC,https://medina.info/,Saudi Arabia,Multi-layered client-server Internet solution,1973,Food Production,9909